=== Blockcast/multicast-api/3gpp/models/associatedprocedure.xsd
<?xml version="1.0" encoding="UTF-8"?> <xs:schema
        xmlns="urn:3gpp:metadata:2005:MBMS:associatedProcedure" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:r12="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-12-extension" xmlns:r13="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension" xmlns:r14="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-14-extension" xmlns:sv="urn:3gpp:metadata:2009:MBMS:schemaVersion" targetNamespace="urn:3gpp:metadata:2005:MBMS:associatedProcedure" elementFormDefault="qualified"
        version="2">
    <xs:import namespace="urn:3gpp:metadata:2009:MBMS:schemaVersion" schemaLocation="schema- version.xsd"/>
    <xs:import namespace="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-12-extension" schemaLocation="adpd-rel-12-extension.xsd"/>
    <xs:import namespace="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension" schemaLocation="adpd-rel-13-extension2.xsd"/>
    <xs:import namespace="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-14-extension" schemaLocation="adpd-rel-14-extension.xsd"/>
    <xs:element name="associatedProcedureDescription" type="associatedProcedureType"/> <xs:complexType name="associatedProcedureType">
    <xs:sequence>
        <xs:element name="postFileRepair" type="basicProcedureType" minOccurs="0"/> <xs:element name="bmFileRepair" type="bmFileRepairType" minOccurs="0"/> <xs:element name="postReceptionReport" type="reportProcedureType" minOccurs="0"/> <xs:element ref="r12:consumptionReport" minOccurs="0"/>
        <xs:element ref="sv:schemaVersion"/>
        <xs:element ref="r13:DASHQoEProcedure" minOccurs="0"/>
        <xs:element ref="sv:delimiter"/>
        <xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="basicProcedureType"> <xs:sequence>
        <xs:element name="serviceURI" type="xs:anyURI" maxOccurs="unbounded"/> </xs:sequence>
        <xs:attribute name="offsetTime" type="xs:unsignedLong" use="optional"/> <xs:attribute name="randomTimePeriod" type="xs:unsignedLong" use="required"/> </xs:complexType>
    <xs:complexType name="bmFileRepairType">
        <xs:attribute name="sessionDescriptionURI" type="xs:anyURI" use="required"/> </xs:complexType>
    <xs:complexType name="reportProcedureType">
        <xs:complexContent>
            <xs:extension base="basicProcedureType">
                <xs:attribute name="samplePercentage" type="xs:decimal" use="optional"
                              default="100"/>
                <xs:attribute name="forceTimeIndependence" type="xs:boolean" use="optional"
                              default="false"/>
                <xs:attribute name="reportType" use="optional" default="RAck">
                    <xs:simpleType>
                        <xs:union memberTypes="knownReportType xs:string"/> </xs:simpleType>
                </xs:attribute>
                <xs:attribute ref="r14:reportInterval"/> </xs:extension>
        </xs:complexContent> </xs:complexType>
    <xs:simpleType name="knownReportType"> <xs:restriction base="xs:string">
        <xs:enumeration value="RAck"/> <xs:enumeration value="StaR"/> <xs:enumeration value="StaR-all"/> <xs:enumeration value="StaR-only"/>
    </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Blockcast/multicast-api/3gpp/models/adp.xml
<?xml version="1.0" encoding="UTF-8"?> <associatedProcedureDescription
        xmlns="urn:3gpp:metadata:2005:MBMS:associatedProcedure" xmlns:sv="urn:3gpp:metadata:2009:MBMS:schemaVersion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:3gpp:metadata:2005:MBMS:associatedProcedure associatedprocedure.xsd"> <postFileRepair
        offsetTime="5"
        randomTimePeriod="10"> <serviceURI>http://mbmsrepair0.example.com/path/repair_script</serviceURI> <serviceURI>http://mbmsrepair1.example.com/path1/repair_script</serviceURI> <serviceURI>http://mbmsrepair2.example.com/path2/repair_script</serviceURI> </postFileRepair>
    <bmFileRepair sessionDescriptionURI="http://www.example.com/3gpp/mbms/session1.sdp"/>
    <postReceptionReport
            offsetTime="5"
            randomTimePeriod="10" reportType="StaR-all" samplePercentage="100" forceTimeIndependence="0">
        <serviceURI>http://mbmsreport.example.com/path/report_script</serviceURI> </postReceptionReport>
    <sv:schemaVersion>1</sv:schemaVersion>
</associatedProcedureDescription>
